[workspace]
resolver = "2"
members = [
    "dway",
    "dway-client-core",
    "dway-ui",
    "dway-ui-derive",
    "dway-server",
    "dway-util",
    "bevy-relationship",
    "bevy-relationship-derive",
    "dway-tty",
]

[workspace.dependencies]
log = "0.4.17"
failure = "0.1.8"
lazy_static = "1.4.0"
uuid = "1.2.2"
memory-stats = "1.1.0"
rand = "0.8"
chrono = "0.4.23"
crossbeam-channel = "0.5.6"
lru = "0.10.0"
nix = "0.26.2"
serde = "1.0.158"
khronos-egl = { version="4.1",features= ["dynamic","static"] }

[patch.crates-io]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_core = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_app = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_utils = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_asset = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_core_pipeline = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_derive = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_ecs = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_math = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_reflect = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_render = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_transform = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_window = { git = "https://github.com/bevyengine/bevy", branch = "main" }
bevy_hierarchy = { git = "https://github.com/bevyengine/bevy", branch = "main" }
