[workspace]
resolver = "2"
members = [
    "dway",
    "dway-client-core",
    "dway-ui", "dway-protocol",
    "dway-server",
    "dway-util",
]

[workspace.dependencies]
log = "0.4.17"
failure = "0.1.8"
lazy_static = "1.4.0"
uuid = "1.2.2"
memory-stats = "1.1.0"
rand = "0.8"
chrono = "0.4.23"
crossbeam-channel = "0.5.6"
lru = "0.10.0"
glow = "0.12.1"
nix = "0.26.2"
serde = "1.0.158"
khronos-egl = { version="4.1",features= ["dynamic","static"] }

kayak_ui ={ version= "0.3.0", rev="50bdb6098ad8a736e9c1faf8fe089670238eb4c3"}

[workspace.dependencies.bevy]
version = "0.10"
features = ["jpeg","wayland", "serialize", "bevy_dynamic_plugin"]

[workspace.dependencies.wgpu]
version = "0.15"
features = ["angle"]

[workspace.dependencies.wgpu-hal]
version = "0.15"
features = ["gles"]

[workspace.dependencies.smithay]
# default-features = false
features = [
    "backend_drm",
    "backend_egl",
    "backend_gbm",
    "backend_libinput",
    "backend_session_libseat",
    "backend_udev",
    "backend_vulkan",
    "desktop",
    "renderer_gl",
    "renderer_multi",
    "slog-stdlog",
    "use_system_lib",
    "xwayland",
]
path = "../smithay"
# git = "https://github.com/Smithay/smithay"

[patch.crates-io]
smithay = {path="../smithay/"}
