[dependencies]
anyhow = "1.0.75"
bevy_framepace = "0.14"
bevy_mod_debugdump = "0.9.0"
bevy_prototype_lyon = "0.10.0"
chrono = "0.4.31"
crossbeam-channel = "0.5.6"
failure = "0.1.8"
lazy_static = "1.4.0"
log = "0.4.17"
lru = "0.12.0"
num_cpus = "1.15.0"
pretty_env_logger = "0.5.0"
rand = "0.8"
uuid = "1.2.2"

[dependencies.bevy]
features = ["jpeg", "wayland", "serialize", "default_font", "subpixel_glyph_atlas"]
version = "0.12"

[dependencies.bevy-inspector-egui]
optional = true
version = "0.21"

[dependencies.clap]
features = ["derive"]
version = "4.4.7"

[dependencies.dexterous_developer]
optional = true
version = "0.0.12"

[dependencies.dway-client-core]
path = "../dway-client-core/"

[dependencies.dway-server]
path = "../dway-server/"

[dependencies.dway-tty]
path = "../dway-tty/"

[dependencies.dway-ui]
path = "../dway-ui/"

[dependencies.dway-util]
path = "../dway-util/"

[dependencies.serde]
optional = true
version = "1"

[dependencies.tracing-subscriber]
features = ["env-filter"]
version = "0.3"

[features]
debug = ["dep:bevy-inspector-egui"]
default = ["dway_log", "debug", "dynamic_reload"]
dway_log = []
dynamic_reload = ["dep:dexterous_developer", "dep:serde", "dway-ui/dynamic_reload"]
eventloop = []
single_thread = []

[lib]
crate-type = ["dylib", "rlib"]
name = "lib_dway"
path = "src/lib.rs"

[package]
edition = "2021"
name = "dway"
version = "0.1.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package.bevy]
opt-level = 3

[profile.dev.package.bevy_prototype_lyon]
debug-assertions = false

[profile.dev.package.lyon_path]
debug-assertions = false

[profile.release]
debug = true
lto = "thin"
